# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-12 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=False)),
                ('bypass_to_localnet', models.BooleanField(default=True)),
                ('av_type', models.IntegerField(choices=[(0, b'eCAP ClamAV Antivirus Module'), (1, b'Third Party ICAP Antivirus Server')], default=0)),
                ('ecap_clamav_async', models.BooleanField(default=False)),
                ('ecap_clamav_message_size_max', models.IntegerField(default=10485760)),
                ('ecap_clamav_on_error_action', models.IntegerField(choices=[(0, b'Allow Object'), (1, b'Deny Object')], default=0)),
                ('ecap_clamav_trickling_enable', models.BooleanField(default=False)),
                ('ecap_clamav_trickling_drop_size', models.IntegerField(default=10)),
                ('ecap_clamav_trickling_period', models.IntegerField(default=10)),
                ('ecap_clamav_trickling_type', models.IntegerField(choices=[(0, b'Trickle only headers'), (1, b'Trickle headers and limited body'), (2, b'Trickle everything')], default=1)),
                ('ecap_clamav_trickling_size_max', models.IntegerField(default=5242880)),
                ('ecap_clamav_trickling_start_delay', models.IntegerField(default=1)),
                ('ecap_reqmod_bypass', models.BooleanField(default=True)),
                ('ecap_respmod_bypass', models.BooleanField(default=True)),
                ('avicap_address', models.CharField(default=b'127.0.0.1', max_length=200)),
                ('avicap_port', models.IntegerField(default=1345)),
                ('avicap_reqpath', models.CharField(default=b'av_scan', max_length=200)),
                ('avicap_respath', models.CharField(default=b'av_scan', max_length=200)),
                ('avicap_res_bypass', models.BooleanField(default=False)),
                ('avicap_options', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SafeBrowsing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=False)),
                ('bypass_to_localnet', models.BooleanField(default=True)),
                ('api_key', models.CharField(max_length=200)),
                ('deny_url', models.CharField(max_length=200)),
                ('check_malware', models.BooleanField(default=True)),
                ('check_social', models.BooleanField(default=True)),
                ('check_unwanted_soft', models.BooleanField(default=False)),
                ('cache_clean', models.IntegerField(default=60)),
                ('daemon_port', models.IntegerField(default=18890)),
                ('helper_verbose', models.BooleanField(default=False)),
                ('helper_total', models.IntegerField(default=20)),
                ('helper_idle', models.IntegerField(default=10)),
                ('helper_startup', models.IntegerField(default=5)),
            ],
        ),
    ]
