# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-12 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('mac', models.CharField(blank=True, max_length=128)),
                ('state', models.CharField(blank=True, max_length=16)),
                ('ip4_config', models.IntegerField(choices=[(0, b'None'), (1, b'DHCP'), (2, b'Static')], default=1)),
                ('ip4_address', models.CharField(blank=True, max_length=254)),
                ('ip4_netmask', models.CharField(blank=True, max_length=254)),
                ('ip4_gateway', models.CharField(blank=True, max_length=254)),
                ('ip4_dns_srv1', models.CharField(blank=True, max_length=254)),
                ('ip4_dns_srv2', models.CharField(blank=True, max_length=254)),
                ('ip4_dns_search', models.CharField(blank=True, max_length=254)),
                ('ip6_config', models.IntegerField(choices=[(0, b'None'), (1, b'DHCP'), (2, b'Static')], default=0)),
                ('ip6_address', models.CharField(blank=True, max_length=254)),
                ('ip6_subnet', models.IntegerField(default=64)),
                ('ip6_gateway', models.CharField(blank=True, max_length=254)),
                ('ip6_dns_srv1', models.CharField(blank=True, max_length=254)),
                ('ip6_dns_srv2', models.CharField(blank=True, max_length=254)),
                ('ip6_dns_search', models.CharField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='NetManual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sharing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_recategorization', models.BooleanField(default=False)),
                ('upload_telemetry_basic', models.BooleanField(default=False)),
                ('upload_telemetry_extended', models.BooleanField(default=False)),
            ],
        ),
    ]
